project_id = "lzitfcigdjbpymvebipp"

[functions.manage-user]
verify_jwt = true

[functions.manage-stock]
verify_jwt = true

[functions.stock-transfer-request]
verify_jwt = true

[functions.inventory-reports]
verify_jwt = true

[functions.low-stock-alerts]
verify_jwt = true

[functions.process-grn]
verify_jwt = true

[functions.process-order-fulfillment]
verify_jwt = true

[functions.process-return-restock]
verify_jwt = true

[functions.manage-purchase-order]
verify_jwt = true
